-- James Morgan

DELETE FROM CUSTOMER;
--Table 1
INSERT INTO CUSTOMER VALUES(1,
	 1,'Cheese',2);
INSERT INTO CUSTOMER VALUES(2,
	 1,null,1);
     
--Table 2
INSERT INTO CUSTOMER VALUES(3,
	 2,null,2);
INSERT INTO CUSTOMER VALUES(4,
	 2,null,1);
INSERT INTO CUSTOMER VALUES(5,
	 2,null,3);
INSERT INTO CUSTOMER VALUES(6,
	 2,null,4);
     
--Table 3
INSERT INTO CUSTOMER VALUES(7,
	 3,null,2);
INSERT INTO CUSTOMER VALUES(8,
	 3,null,1);
INSERT INTO CUSTOMER VALUES(9,
	 3,null,4);

--Table 4
INSERT INTO CUSTOMER VALUES(10,
	 4,null,2);
INSERT INTO CUSTOMER VALUES(11,
	 4,null,3);
INSERT INTO CUSTOMER VALUES(12,
	 4,null,4);

--Table 5
INSERT INTO CUSTOMER VALUES(13,
	 5,'peanut',2);
INSERT INTO CUSTOMER VALUES(14,
	 5,null,3);
INSERT INTO CUSTOMER VALUES(15,
	 5,null,4);

--Table 6
INSERT INTO CUSTOMER VALUES(16,
	 6,null,2);
INSERT INTO CUSTOMER VALUES(17,
	 6,null,3);
INSERT INTO CUSTOMER VALUES(18,
	 6,null,1);
INSERT INTO CUSTOMER VALUES(19,
	 6,null,4);

--Table 7
INSERT INTO CUSTOMER VALUES(20,
	 7,null,2);
INSERT INTO CUSTOMER VALUES(21,
	 7,null,3);
INSERT INTO CUSTOMER VALUES(22,
	 7,null,1);
INSERT INTO CUSTOMER VALUES(23,
	 7,null,4);
INSERT INTO CUSTOMER VALUES(24,
	 7,null,6);
INSERT INTO CUSTOMER VALUES(25,
	 7,null,5);
INSERT INTO CUSTOMER VALUES(26,
	 7,null,8);
INSERT INTO CUSTOMER VALUES(27,
	 7,null,7);
     
--Table 8
INSERT INTO CUSTOMER VALUES(28,
	 8,null,2);
INSERT INTO CUSTOMER VALUES(29,
	 8,null,3);
INSERT INTO CUSTOMER VALUES(30,
	 8,null,1);
INSERT INTO CUSTOMER VALUES(31,
	 8,null,4);

--Table 9
INSERT INTO CUSTOMER VALUES(32,
	 9,null,1);
INSERT INTO CUSTOMER VALUES(33,
	 9,null,3);
INSERT INTO CUSTOMER VALUES(34,
	 9,null,2);
INSERT INTO CUSTOMER VALUES(35,
	 9,null,4);     

--Table 10
INSERT INTO CUSTOMER VALUES(36,
	 10,null,1);
INSERT INTO CUSTOMER VALUES(37,
	 10,null,3);
INSERT INTO CUSTOMER VALUES(38,
	 10,null,2);
INSERT INTO CUSTOMER VALUES(39,
	 10,null,4); 

--Table 11
INSERT INTO CUSTOMER VALUES(40,
     11,null,1);
INSERT INTO CUSTOMER VALUES(41,
	 11,null,3);
     
--Table 12
INSERT INTO CUSTOMER VALUES(42,
	 12,null,2);
INSERT INTO CUSTOMER VALUES(43,
	 12,null,4);  

--Table 13
INSERT INTO CUSTOMER VALUES(44,
	 13,null,4); 
     
--Table 14
INSERT INTO CUSTOMER VALUES(45,
	 14,null,1);
INSERT INTO CUSTOMER VALUES(46,
	 14,'nuts',3);
INSERT INTO CUSTOMER VALUES(47,
	 14,null,2);
INSERT INTO CUSTOMER VALUES(48,
	 14,null,4); 

--Table 15
INSERT INTO CUSTOMER VALUES(49,
	 15,null,3);
INSERT INTO CUSTOMER VALUES(50,
	 15,null,2);
INSERT INTO CUSTOMER VALUES(51,
	 15,null,4); 

--Table 16
INSERT INTO CUSTOMER VALUES(52,
	 16,null,3);
INSERT INTO CUSTOMER VALUES(53,
	 16,null,2);
INSERT INTO CUSTOMER VALUES(54,
	 16,null,4); 

--Table 17
INSERT INTO CUSTOMER VALUES(55,
	 17,null,3);
INSERT INTO CUSTOMER VALUES(56,
	 17,null,2);
INSERT INTO CUSTOMER VALUES(57,
	 17,null,4); 
INSERT INTO CUSTOMER VALUES(58,
	 17,null,4); 
     
--Table 18
INSERT INTO CUSTOMER VALUES(59,
	 18,null,2);
INSERT INTO CUSTOMER VALUES(60,
	 18,null,3);
INSERT INTO CUSTOMER VALUES(61,
	 18,'beans',1);
INSERT INTO CUSTOMER VALUES(62,
	 18,null,4);
INSERT INTO CUSTOMER VALUES(63,
	 18,null,6);
INSERT INTO CUSTOMER VALUES(64,
	 18,null,5);
INSERT INTO CUSTOMER VALUES(65,
	 18,null,8);
INSERT INTO CUSTOMER VALUES(66,
	 18,null,9);
INSERT INTO CUSTOMER VALUES(67,
	 18,null,7);

--Table 19
INSERT INTO CUSTOMER VALUES(68,
	 19,null,3);
     
--INSERT INTO MEAL VALUES('plain slice', seqSID.nextVal,3.50, 'cheese'
--);
/*     
DELETE FROM SERVER;
--Jason Lee Scott, Kimberly Hart, Zack Taylor, Trini Kwan and Billy Cranston
INSERT INTO SERVER VALUES('Jason_Lee_Scott', 1, 
);

INSERT INTO SERVER VALUES('Jason_Lee_Scott', 6, 
);

INSERT INTO SERVER VALUES('Jason_Lee_Scott', 8, 
);
INSERT INTO SERVER VALUES('Jason_Lee_Scott', 9, 
);
INSERT INTO SERVER VALUES('Jason_Lee_Scott', 11, 
);

INSERT INTO SERVER VALUES('Jason_Lee_Scott', 18, 
INSERT INTO SERVER VALUES('Kimberly_Hart', 2, 
INSERT INTO SERVER VALUES('Kimberly_Hart', 12, 
INSERT INTO SERVER VALUES('Kimberly_Hart', 5, 
INSERT INTO SERVER VALUES('Kimberly_Hart', 7, 
INSERT INTO SERVER VALUES('Kimberly_Hart', 13, 
INSERT INTO SERVER VALUES('Kimberly_Hart', 15, 
INSERT INTO SERVER VALUES('Kimberly_Hart', 17, 

INSERT INTO SERVER VALUES('Trini_Kwan',3,
INSERT INTO SERVER VALUES('Trini_Kwan',4,
INSERT INTO SERVER VALUES('Trini_Kwan',11,
INSERT INTO SERVER VALUES('Trini_Kwan',14,
INSERT INTO SERVER VALUES('Trini_Kwan',16,
INSERT INTO SERVER VALUES('Trini_Kwan',10,
INSERT INTO SERVER VALUES('Trini_Kwan',19,
     
